### PR TITLE
Test

### PR DESCRIPTION
**Pull request by Weedy0104**
Test

### CODE REVIEW

**Comment by ghost** [comment]
Stop sending stupid Pull Requests!!!! The dev is spending time to close your stupid PR, when he can develop the kernel. So stop!!!!

**Comment by Weedy0104** [comment]
Hey sorry i am new to github and didnt know what it does. Thanks for your
Email wont do it again

ExtremeGrief <notifications@github.com> schrieb am Sa., 11. Apr. 2020,
21:24:

**Comment by evdenis** [comment]
Please, don't worry. I perfectly understand that it's not intentional. It's hard for non-devs to deal with all these developer instruments and, of course, my instructions on xda or readme.md can't cover all aspects. I takes me little to nothing to close these occasional pull requests.

**Comment by evdenis** [comment]
Personally, I like to observe sometimes what configs people are trying to use.

**Pull request closed without merging**
